name: generatebib

on: 
  workflow_dispatch:
  schedule: #  UTC min hour day month dayOfWeek
           - cron: '03 6 * * *'

jobs:
  bib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          python -m pip install algoliasearch


      - name: Generate bibfile
        run: |
          wc -l texmf/bibtex/bib/lsst.bib
          make lsst.bib
          wc -l texmf/bibtex/bib/lsst.bib

      - name: Commit new bib
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m " generated lsst.bib " texmf/bibtex/bib/lsst.bib

      - name: Check diff
        run: | #  set an environment variable
           if git diff --exit-code; then
              echo "CHANGED=false" >> ${GITHUB_ENV}
              echo "No changes - no PR"
           else
              echo "CHANGED=true" >> ${GITHUB_ENV}
              echo "Git changes - should make PR"
           fi
           echo "env.CHANGED ${CHANGED}"

      - name: Create Pull Request
        if: env.CHANGED == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WOM_UPDATEBIB_PAT }}
          branch: update-bibfile
          branch-suffix: short-commit-hash
          title: Automatic bibfile  update 
          commit-message: bibgile update
          body: Update bibfile from lsst.io and etc/static_entries.bib
